Ext.define('CDBE.model.aree.Aree', {
    extend: 'Ext.data.Model',
    fields: [
        {name :'ANNO_RIL', type :'string'},
        {name :'IDAREA', type :'string'},
        {name :'TIPOAREA', type :'string', defaultValue: "0"},
        {name :'PAESE', type :'string', defaultValue: "0"},
        {name :'PROVINCI', type :'string', defaultValue: "0"},
        {name :'COMUNE', type :'string', defaultValue: "0"},
        {name :'IDSQUADRA', type :'string', defaultValue: "0"},
        {name :'IDONEITA', type :'string', defaultValue: "0"},
        {name :'DATARIL', type :'date', defaultValue: new Date(1900, 1, 1)},
        {name :'COORDN', type :'double', defaultValue: 0},
        {name :'COORDE', type :'double', defaultValue: 0},
        {name :'ALTITUD', type :'string', defaultValue: "0"},
        {name :'ESPOSIZ', type :'string', defaultValue: "0"},
        {name :'DISPH2O', type :'string', defaultValue: "0"},
        {name :'T_HUMUS', type :'string', defaultValue: "0"},
        {name :'ETAMEDIA', type :'string', defaultValue: "0"},
        {name :'CATFOR', type :'string', defaultValue: "0"},
        {name :'SCATFOR', type :'string', defaultValue: "0"},
        {name :'COORDN_C', type :'double', defaultValue: 0},
        {name :'COORDE_C', type :'double', defaultValue: 0},
        {name :'FIXGPS_C', type :'int', defaultValue: 0},
        {name :'PIC', type :'string', defaultValue: "0"},
        {name :'TRAS_PIC', type :'string', defaultValue: "0"},
        {name :'T_PIC_AZ', type :'double', defaultValue: 0},
        {name :'T_PIC_DS', type :'double', defaultValue: 0},
        {name :'DATAUP', type :'date', defaultValue: new Date(1900, 1, 1)},
    ]
});
